from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, Optional
import json
import logging

import numpy as np

from eaa_core.message_proc import generate_openai_message
from eaa_core.skill import SkillMetadata, split_markdown_into_message_sections
from eaa_core.tool.base import (
    BaseTool,
    ExposedToolSpec,
    TOOL_IMAGE_PATH_FIELD,
    normalize_tool_result,
    generate_openai_tool_schema,
)

logger = logging.getLogger(__name__)


@dataclass
class ToolExecutionResult:
    """Normalized tool execution result."""

    message: dict[str, Any]


class SerialToolExecutor:
    """Serial, thread-free tool execution for task managers."""

    def __init__(
        self,
        approval_handler: Optional[Callable[[str, Dict[str, Any]], bool]] = None,
    ) -> None:
        """Initialize the executor."""
        self.approval_handler = approval_handler
        self.tools: list[BaseTool] = []
        self.tool_specs: dict[str, ExposedToolSpec] = {}
        self.tool_execution_history: list[dict[str, Any]] = []

    def register_tools(self, tools: BaseTool | list[BaseTool]) -> None:
        """Register one or more tool objects."""
        if not isinstance(tools, (list, tuple)):
            tools = [tools]
        for tool in tools:
            if not isinstance(tool, BaseTool):
                raise ValueError("Input should be a BaseTool or a list of BaseTool objects.")
            self.tools.append(tool)
            for exposed in tool.exposed_tools:
                spec = ExposedToolSpec(
                    name=exposed.name,
                    function=exposed.function,
                    require_approval=(
                        tool.require_approval if exposed.require_approval is None else exposed.require_approval
                    ),
                    schema=exposed.schema,
                )
                self.tool_specs[spec.name] = spec

    def list_tool_schemas(self) -> list[dict[str, Any]]:
        """Return model-facing OpenAI tool schemas."""
        return [
            spec.schema or generate_openai_tool_schema(tool_name=name, func=spec.function)
            for name, spec in self.tool_specs.items()
        ]

    def execute_tool_calls(self, tool_calls: list[dict[str, Any]]) -> list[ToolExecutionResult]:
        """Execute assistant-requested tool calls serially."""
        return [self.execute_tool_call(tool_call) for tool_call in tool_calls]

    def execute_tool_calls_from_message(
        self,
        message: dict[str, Any],
    ) -> list[dict[str, Any]]:
        """Execute tool calls found in an assistant message.

        Parameters
        ----------
        message : dict[str, Any]
            Assistant message that may contain tool calls.
        Returns
        -------
        list[dict[str, Any]]
            Tool messages generated by the executed tool calls.
        """
        tool_calls = message.get("tool_calls")
        if not isinstance(tool_calls, list) or len(tool_calls) == 0:
            return []
        results = self.execute_tool_calls(tool_calls)
        return [result.message for result in results]

    def execute_tool_call(self, tool_call: dict[str, Any]) -> ToolExecutionResult:
        """Execute one tool call and normalize its response."""
        function = tool_call.get("function", {})
        tool_name = function.get("name")
        if tool_name not in self.tool_specs:
            raise ValueError(f"Unknown tool requested: {tool_name}")
        spec = self.tool_specs[tool_name]
        arguments = self.parse_arguments(function.get("arguments"))
        if spec.require_approval and self.approval_handler is not None:
            approved = self.approval_handler(tool_name, arguments)
            if not approved:
                message = generate_openai_message(
                    content=self.serialize_result({"error": "Tool execution was denied by the user."}),
                    role="tool",
                    tool_call_id=tool_call.get("id"),
                )
                return ToolExecutionResult(message=message)
        try:
            result = spec.function(**arguments)
            content = self.serialize_result(result)
        except Exception as exc:
            logger.exception("Tool execution failed for %s", tool_name)
            content = self.serialize_result({"error": str(exc)})
        message = generate_openai_message(
            content=content,
            role="tool",
            tool_call_id=tool_call.get("id"),
        )
        self.tool_execution_history.append({"tool_name": tool_name, "arguments": arguments})
        return ToolExecutionResult(message=message)

    @staticmethod
    def parse_arguments(arguments: Any) -> dict[str, Any]:
        """Parse assistant-provided tool arguments."""
        if arguments is None:
            return {}
        if isinstance(arguments, dict):
            return arguments
        if not isinstance(arguments, str):
            raise ValueError(f"Unsupported tool argument payload: {type(arguments)}")
        stripped = arguments.strip()
        if len(stripped) == 0:
            return {}
        parsed = json.loads(stripped)
        if not isinstance(parsed, dict):
            raise ValueError("Tool arguments must decode into a dictionary.")
        return parsed

    @staticmethod
    def parse_tool_response_payload(content: Any) -> Optional[Dict[str, Any]]:
        """Parse dict-like tool payloads from tool message content.

        Parameters
        ----------
        content : Any
            Tool message content payload.

        Returns
        -------
        dict[str, Any] or None
            Parsed dictionary payload when available.
        """
        if isinstance(content, dict):
            return content
        if not isinstance(content, str):
            return None
        try:
            parsed = json.loads(content)
        except json.JSONDecodeError:
            return None
        return parsed if isinstance(parsed, dict) else None

    @classmethod
    def extract_image_paths_from_tool_response(cls, content: Any) -> list[str]:
        """Extract one or more image paths from a tool response payload.

        Parameters
        ----------
        content : Any
            Tool message content payload.

        Returns
        -------
        list[str]
            Extracted image paths.
        """
        payload = cls.parse_tool_response_payload(content)
        if payload is not None:
            image_path = payload.get(TOOL_IMAGE_PATH_FIELD)
            if isinstance(image_path, list):
                return [value for value in image_path if isinstance(value, str)]
            if isinstance(image_path, str):
                return [image_path]
            legacy_image_paths = payload.get("image_paths")
            if isinstance(legacy_image_paths, list):
                return [value for value in legacy_image_paths if isinstance(value, str)]
            legacy_image_path = payload.get("image_path")
            if isinstance(legacy_image_path, str):
                return [legacy_image_path]
            return []
        return []

    @classmethod
    def build_skill_doc_messages(
        cls,
        tool_response: Dict[str, Any],
        tool_call_info: Optional[Dict[str, Any]],
        skill_catalog: list[SkillMetadata],
    ) -> list[Dict[str, Any]]:
        """Expand skill-documentation tool payloads into OpenAI messages.

        Parameters
        ----------
        tool_response : dict[str, Any]
            Tool response message containing the documentation payload.
        tool_call_info : dict[str, Any], optional
            Tool call metadata from the originating assistant message.
        skill_catalog : list[SkillMetadata]
            Skills available to the task manager.

        Returns
        -------
        list[dict[str, Any]]
            Message sequence extracted from the skill documentation payload.
        """
        if tool_call_info is None:
            return []
        tool_name = tool_call_info.get("function", {}).get("name")
        skill_tool_names = {skill.tool_name for skill in skill_catalog}
        if tool_name not in skill_tool_names:
            return []
        payload = cls.parse_tool_response_payload(tool_response.get("content"))
        if payload is None or not isinstance(payload.get("files"), dict):
            return []
        skill_root = payload.get("path")
        skill_root_path = Path(skill_root) if isinstance(skill_root, str) else None
        messages = []
        for relative_path, file_content in payload["files"].items():
            if not isinstance(relative_path, str) or not isinstance(file_content, str):
                continue
            markdown_path = skill_root_path / relative_path if skill_root_path is not None else None
            for section in split_markdown_into_message_sections(
                file_content,
                markdown_path=markdown_path,
            ):
                if len(section["image_paths"]) == 0:
                    messages.append(generate_openai_message(content=section["text"], role="user"))
                    continue
                try:
                    messages.append(
                        generate_openai_message(
                            content=section["text"],
                            role="user",
                            image_path=section["image_paths"][0],
                        )
                    )
                except Exception as exc:
                    logger.warning(
                        "Failed to load skill image '%s': %s",
                        section["image_paths"][0],
                        exc,
                    )
                    messages.append(generate_openai_message(content=section["text"], role="user"))
                for image_path in section["image_paths"][1:]:
                    try:
                        messages.append(generate_openai_message(content="", role="user", image_path=image_path))
                    except Exception as exc:
                        logger.warning("Failed to load skill image '%s': %s", image_path, exc)
        return messages

    @classmethod
    def build_tool_followup_messages(
        cls,
        tool_response: Dict[str, Any],
        *,
        skill_catalog: list[SkillMetadata],
        message_with_yielded_image: str,
        allow_non_image_tool_responses: bool,
        tool_call_info: Optional[Dict[str, Any]] = None,
    ) -> list[dict[str, Any]]:
        """Generate follow-up messages after a tool finishes.

        Parameters
        ----------
        tool_response : dict[str, Any]
            Normalized tool response message.
        skill_catalog : list[SkillMetadata]
            Skills available to the task manager.
        message_with_yielded_image : str
            User-facing text used when an image path is returned.
        allow_non_image_tool_responses : bool
            Whether non-image tool results are acceptable in the current flow.
        tool_call_info : dict[str, Any], optional
            Tool call metadata from the originating assistant message.

        Returns
        -------
        list[dict[str, Any]]
            Follow-up messages to append after tool execution.
        """
        followup_messages = cls.build_skill_doc_messages(
            tool_response,
            tool_call_info,
            skill_catalog,
        )
        image_paths = cls.extract_image_paths_from_tool_response(tool_response.get("content"))
        if len(image_paths) > 0:
            followup_messages.append(
                generate_openai_message(
                    content=message_with_yielded_image,
                    image_path=image_paths,
                    role="user",
                )
            )
        elif not allow_non_image_tool_responses:
            followup_messages.append(cls.build_non_image_tool_warning())
        return followup_messages

    @staticmethod
    def build_non_image_tool_warning() -> dict[str, Any]:
        """Build a warning message for unexpected non-image tool results.

        Returns
        -------
        dict[str, Any]
            User message warning about the unexpected tool result type.
        """
        return generate_openai_message(
            content=(
                "The tool should return a JSON payload with a valid `img_path`, "
                "but no image path was found. Make sure you called the right tool correctly."
            ),
            role="user",
        )

    @staticmethod
    def serialize_result(result: Any) -> str:
        """Serialize a tool result into normalized JSON content."""
        return json.dumps(normalize_tool_result(result), default=SerialToolExecutor._json_default)

    @staticmethod
    def _json_default(value: Any) -> Any:
        """Convert common non-JSON-native tool values into serializable forms."""
        if isinstance(value, np.ndarray):
            return value.tolist()
        if isinstance(value, np.generic):
            return value.item()
        if isinstance(value, Path):
            return str(value)
        if isinstance(value, tuple):
            return list(value)
        raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")
