# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  EAA_CI_DATA_DIR: /local/eaa_ci_data/
  CONDA_EXE: /local/actions-env/miniconda3/condabin/conda
  CONDA_ROOT: /local/actions-env/miniconda3/

permissions:
  contents: read

jobs:
  lint:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Activate environment
        id: activate_env
        run: |
          source $CONDA_ROOT/bin/activate ci_py311_base

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check src/ --output-format=github

  linux-x86-gpu:

    defaults:
      run:
        shell: bash -l {0}

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Update test data
      id: update_test_data
      run: |
        PACKAGE_DIR=$(pwd)
        cd $PTYCHO_CI_DATA_DIR
        git pull origin main
        cd $PACKAGE_DIR

    - name: Create environment
      id: create_env
      run: |
        export ENVNAME=ci_py311_$(date +%s)
        $CONDA_EXE create --quiet --yes --force -n $ENVNAME python=3.11
        echo "ENVNAME=$ENVNAME" >> $GITHUB_ENV
      
    - name: Install dependencies
      run: |
        echo "Current working directory: $PWD"
        $CONDA_EXE env list
        source $CONDA_ROOT/bin/activate $ENVNAME
        $CONDA_ROOT/envs/$ENVNAME/bin/pip install --upgrade pip
        $CONDA_ROOT/envs/$ENVNAME/bin/pip install uv
        uv venv .venv --python 3.11
        source .venv/bin/activate
        if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
        uv pip install -e .
        uv pip install pytest
        uv pip list

    - name: Test with pytest
      run: |
        echo "Current working directory: $PWD"
        source .venv/bin/activate
        echo $(which python)
        cd tests
        pytest -s --high-tol

    - name: Remove environment
      if: always()
      run: |
        $CONDA_EXE remove -n $ENVNAME --all --yes --force
  